version: '3.8'

services:

  db:
    image: postgres:9.6.21
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
    ports:
      - '25432:5432'
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: zakadabar-template/version
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'